services:
  payli-api:
    environment:
      DB_URI: mongodb://mongo:27017
      LOG_FILE_PATH: /app/storage/${LOG_FILENAME}
    build: .
    restart: unless-stopped
    volumes:
      - '${LOG_DIRNAME}:/app/storage'
      - /app/node_modules
    networks:
      - api
    ports:
      - '127.0.0.1:3030:3000'

networks:
  api:
    name: api
    external: true
