export const TOKENS = {
  USDC: {
    symbol: 'USDC',
    name: 'USD Coin',
    decimals: 6,
    contractAddresses: {
      mainnet: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      bsc: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',
      polygon: '0x3c499959c92e8d5b2b6d8b6e9d8b6e9d8b6e9d8b',
      base: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      arbitrum: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
      optimism: '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',
      celoMainnet: '0xcebA9300f2b948710d2653dD7B07f33A8B32118C',
    },
  },
  USDT: {
    symbol: 'USDT',
    name: 'Tether USD',
    decimals: 6,
    contractAddresses: {
      mainnet: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
      bsc: '0x55d398326f99059fF775485246999027B3197955',
      polygon: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
      base: '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2',
      arbitrum: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
      optimism: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58',
      celoMainnet: '0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e',
    },
  },
  ETH: {
    symbol: 'ETH',
    name: 'Ethereum',
    decimals: 18,
    isNative: true,
    contractAddresses: {},
  },
  BNB: {
    symbol: 'BNB',
    name: 'Binance Coin',
    decimals: 18,
    isNative: true,
    contractAddresses: {},
  },
  POL: {
    symbol: 'POL',
    name: 'Polygon',
    decimals: 18,
    isNative: true,
    contractAddresses: {},
  },
  CELO: {
    symbol: 'CELO',
    name: 'Celo',
    decimals: 18,
    isNative: true,
    contractAddresses: {},
  },
  SOL: {
    symbol: 'SOL',
    name: 'Solana',
    decimals: 9,
    isNative: true,
    isNonEvm: true,
  },
  BTC: {
    symbol: 'BTC',
    name: 'Bitcoin',
    decimals: 8,
    isNative: true,
    isNonEvm: true,
  },
  XLM: {
    symbol: 'XLM',
    name: 'Stellar Lumens',
    decimals: 7,
    isNative: true,
    isNonEvm: true,
  },
  TRX: {
    symbol: 'TRX',
    name: 'Tron',
    decimals: 6,
    isNative: true,
    isNonEvm: true,
  },
};

export const NETWORKS = {
  ethereum: {
    id: 'ethereum',
    name: 'Ethereum',
    chainId: 1,
    type: 'evm',
    rpcUrl: 'https://eth.llamarpc.com',
    blockExplorer: 'https://etherscan.io',
    nativeToken: TOKENS.ETH,
    supportedTokens: [TOKENS.USDC, TOKENS.USDT, TOKENS.ETH],
  },
  bsc: {
    id: 'bsc',
    name: 'BNB Chain',
    chainId: 56,
    type: 'evm',
    rpcUrl: 'https://bsc-dataseed.binance.org',
    blockExplorer: 'https://bscscan.com',
    nativeToken: TOKENS.BNB,
    supportedTokens: [TOKENS.USDC, TOKENS.USDT, TOKENS.BNB],
  },
  polygon: {
    id: 'polygon',
    name: 'Polygon',
    chainId: 137,
    type: 'evm',
    rpcUrl: 'https://polygon-rpc.com',
    blockExplorer: 'https://polygonscan.com',
    nativeToken: TOKENS.POL,
    supportedTokens: [TOKENS.USDC, TOKENS.USDT, TOKENS.POL],
  },
  base: {
    id: 'base',
    name: 'Base',
    chainId: 8453,
    type: 'evm',
    rpcUrl: 'https://mainnet.base.org',
    blockExplorer: 'https://basescan.org',
    nativeToken: TOKENS.ETH,
    supportedTokens: [TOKENS.USDC, TOKENS.USDT, TOKENS.ETH],
  },
  arbitrum: {
    id: 'arbitrum',
    name: 'Arbitrum',
    chainId: 42161,
    type: 'evm',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    blockExplorer: 'https://arbiscan.io',
    nativeToken: TOKENS.ETH,
    supportedTokens: [TOKENS.USDC, TOKENS.USDT, TOKENS.ETH],
  },
  optimism: {
    id: 'optimism',
    name: 'Optimism',
    chainId: 10,
    type: 'evm',
    rpcUrl: 'https://mainnet.optimism.io',
    blockExplorer: 'https://optimistic.etherscan.io',
    nativeToken: TOKENS.ETH,
    supportedTokens: [TOKENS.USDC, TOKENS.USDT, TOKENS.ETH],
  },
  celo: {
    id: 'celo',
    name: 'Celo',
    chainId: 42220,
    type: 'evm',
    rpcUrl: 'https://forno.celo.org',
    blockExplorer: 'https://celoscan.io',
    nativeToken: TOKENS.CELO,
    supportedTokens: [TOKENS.USDC, TOKENS.USDT, TOKENS.CELO],
  },
  solana: {
    id: 'solana',
    name: 'Solana',
    type: 'non-evm',
    rpcUrl: 'https://api.mainnet-beta.solana.com',
    blockExplorer: 'https://explorer.solana.com',
    nativeToken: TOKENS.SOL,
    supportedTokens: [TOKENS.SOL],
  },
  bitcoin: {
    id: 'bitcoin',
    name: 'Bitcoin',
    type: 'non-evm',
    rpcUrl: 'https://blockstream.info/api',
    blockExplorer: 'https://blockstream.info',
    nativeToken: TOKENS.BTC,
    supportedTokens: [TOKENS.BTC],
  },
  stellar: {
    id: 'stellar',
    name: 'Stellar',
    type: 'non-evm',
    rpcUrl: 'https://horizon.stellar.org',
    blockExplorer: 'https://stellar.expert',
    nativeToken: TOKENS.XLM,
    supportedTokens: [TOKENS.XLM],
  },
  tron: {
    id: 'tron',
    name: 'Tron',
    type: 'non-evm',
    rpcUrl: 'https://api.trongrid.io',
    blockExplorer: 'https://tronscan.org',
    nativeToken: TOKENS.TRX,
    supportedTokens: [TOKENS.TRX],
  },
};
